[package]
name = "gpu-driver"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
common = { path = "../common" }  # 依赖共享模块
x86_64 = { workspace = true, features = ["instructions"] }
