[package]
name = "rui-lib"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib"]  # 静态库，供应用链接

[dependencies]
common = { path = "../common" }
x86_64 = { workspace = true }
