[package]
name = "render"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
common = { path = "../common" }
x86_64 = { workspace = true, features = ["instructions"] }
font8x8.workspace = true  # 依赖字体库
